name: YouTube Summarizer

on:
  schedule:
    # Türkiye saatiyle 16:35 = UTC+3, yani UTC 13:35
    - cron: '45 13 * * *'
  workflow_dispatch:

jobs:
  run-summarizer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py
